<a href="https://colab.research.google.com/github/irinavalenzuela/Applied-Data-Science-Python/blob/main/Week1_Intro_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Data Science in Python

## Week 1
### Numerical Python Library

In [6]:
# Import numpy
import numpy as np
import math

In [7]:
# Array Creation

# The argument of an array is a list
a = np.array([2,3,4])
print(a)

# Print the number of dimensions of a list using ndim
print(a.ndim)

[2 3 4]
1


In [10]:
# List of lists in numpy array --> Matrix
b = np.array([[1,4,5],[4,6,8]])
b

# Print the lengh of each dimension: shape attribute
b.shape

(2, 3)

In [11]:
# Check the type of items in the array
a.dtype
b.dtype

dtype('int64')

In [12]:
# Lets create two arrays
d = np.zeros((2,3))
print(d)

e=np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# Array with random numbers

np.random.rand(2,3)

array([[0.38792015, 0.97494855, 0.88281443],
       [0.4796278 , 0.77931887, 0.77234743]])

In [ ]:
# Array of every even number from 10 to 50
f = np.arange(10,50,2)
f

In [18]:
# linspace: sequence of floats from 0 to 2, the 3rd argument is the total number of items
np.linspace(0,2,15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [ ]:
# Array operations


In [19]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

# A - B
c = a-b
print(c)

# A times B
d = a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [29]:
# Convert F to Celcius
farenheit = np.array([0, -23,-10,0])

# Conversion formula: C = (F-32) * 5/9
celcius = (farenheit - 32) * 5/9
celcius

array([-17.77777778, -30.55555556, -23.33333333, -17.77777778])

In [30]:
# Boolean Array: true emitted if meets the condition

# Celcius degree greater than -20
celcius>-20

array([ True, False, False,  True])

In [31]:
# Modulus operator to see if an array is even (if divide by 2, then remainder shoud be 0)
celcius%2 ==0

array([False, False, False, False])

In [32]:
# Matrix product: elementwise product

A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print(A*B)

# Matrix product
print(A@B)


[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [33]:
# See the shape of a matrix
A.shape
B.shape

(2, 2)

In [36]:
# Arrays of different types. The resulting array will be the more general of the two types (upscastiing)

# Array of integers
array1 = np.array([[1,2,3],[4,5,6]])
print(array1.dtype)

# Array of floats
array2 = np.array([[7.1,8.2,9.1],[10.4,11.2,12.3]])
print(array2.dtype)

# Addition
array3 = array1 + array2
print(array3) # the resulting array have been upcast into floating numbers
print(array3.dtype)

int64
float64
[[ 8.1 10.2 12.1]
 [14.4 16.2 18.3]]
float64


In [37]:
# Aggregation functions

print(array3.sum())
print(array3.min())
print(array2.max())
print(array1.mean())

79.3
8.1
12.3
3.5


In [39]:
# Create an array with 15 elements with a dim 3x5

b = np.arange(1,16,1).reshape(3,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [45]:
# Use python imaging library (PIL) 
# Function to display images in the notebook
from PIL import Image
from IPython.display import display


im= Image.open(chris)
display(im)


FileNotFoundError: ignored