<a href="https://colab.research.google.com/github/irinavalenzuela/Applied-Data-Science-Python/blob/main/Week1_Intro_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Data Science in Python

## Week 1
### Numerical Python Library

In [6]:
# Import numpy
import numpy as np
import math

In [7]:
# Array Creation

# The argument of an array is a list
a = np.array([2,3,4])
print(a)

# Print the number of dimensions of a list using ndim
print(a.ndim)

[2 3 4]
1


In [10]:
# List of lists in numpy array --> Matrix
b = np.array([[1,4,5],[4,6,8]])
b

# Print the lengh of each dimension: shape attribute
b.shape

(2, 3)

In [11]:
# Check the type of items in the array
a.dtype
b.dtype

dtype('int64')

In [12]:
# Lets create two arrays
d = np.zeros((2,3))
print(d)

e=np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# Array with random numbers

np.random.rand(2,3)

array([[0.38792015, 0.97494855, 0.88281443],
       [0.4796278 , 0.77931887, 0.77234743]])

In [ ]:
# Array of every even number from 10 to 50
f = np.arange(10,50,2)
f

In [18]:
# linspace: sequence of floats from 0 to 2, the 3rd argument is the total number of items
np.linspace(0,2,15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [ ]:
# Array operations


In [19]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

# A - B
c = a-b
print(c)

# A times B
d = a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]
